# Generated by Django 4.2.1 on 2023-06-04 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_appuser_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='post_category',
        ),
        migrations.DeleteModel(
            name='BlogPostCategory',
        ),
    ]
