# Generated by Django 4.2.1 on 2023-06-12 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_rename_user_blogpost_author_remove_blogpost_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='tags',
        ),
    ]
